# Generated by Django 3.2.9 on 2021-11-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.TextField(default=0, verbose_name='Chosen language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.FloatField(default=0, verbose_name='User`s money'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
    ]
