# Generated by Django 3.2.9 on 2021-11-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20211101_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text of the questions')),
                ('number', models.PositiveIntegerField(verbose_name='Number of the question')),
            ],
            options={
                'verbose_name': 'Answers to ther question',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.TextField(verbose_name='Greeting')),
                ('select_lang', models.TextField(verbose_name='Select language')),
            ],
            options={
                'verbose_name': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('right_choice', models.IntegerField(verbose_name='Right choice')),
                ('number', models.PositiveIntegerField(verbose_name='Number of the qustion')),
            ],
            options={
                'verbose_name': 'Question',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.TextField(default='Ru', verbose_name='Chosen language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.FloatField(default=0, verbose_name='User`s money'),
        ),
    ]
