# Generated by Django 3.2.9 on 2021-11-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20211102_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Answers to the question'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Users profile'},
        ),
        migrations.AddField(
            model_name='language',
            name='ans_ques',
            field=models.TextField(default=0, verbose_name='Answer to question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='post',
            field=models.TextField(default=0, verbose_name='Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='profile',
            field=models.TextField(default=0, verbose_name='Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='question',
            field=models.TextField(default=0, verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='wallet',
            field=models.TextField(default=0, verbose_name='My Wallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='prize',
            field=models.FloatField(default=0, verbose_name='Prize fund'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='winners_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of winners'),
            preserve_default=False,
        ),
    ]
