# Generated by Django 3.2.9 on 2021-11-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.TextField(default='RU', verbose_name='Chosen language'),
        ),
    ]
