# Generated by Django 3.2.9 on 2021-11-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_alter_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lang_choose',
            field=models.TextField(default=0, verbose_name='Chosen language'),
            preserve_default=False,
        ),
    ]
