# Generated by Django 3.2.9 on 2021-11-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_language_lang_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='balance',
            field=models.TextField(default=0, verbose_name='Your balance:'),
            preserve_default=False,
        ),
    ]
