# Generated by Django 3.2.9 on 2021-11-02 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_language_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Available at this time:'),
        ),
    ]
