# Generated by Django 3.2.9 on 2021-11-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0009_question_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='of_question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ugc.question'),
            preserve_default=False,
        ),
    ]
