# Generated by Django 3.2.9 on 2021-11-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0010_answers_of_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='name',
        ),
    ]
