# Generated by Django 3.2.9 on 2021-11-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0012_rename_text_answers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.TextField(default='Inactive', verbose_name='Question status'),
        ),
    ]
