# Generated by Django 3.2.9 on 2021-11-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0013_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chosen_ques',
            field=models.TextField(default=0, verbose_name='Chosen question'),
        ),
    ]
