# Generated by Django 3.2.9 on 2021-11-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0014_profile_chosen_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='correct',
            field=models.TextField(default=0, verbose_name='Correct answer!'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='wrong',
            field=models.TextField(default=0, verbose_name='Wrong answer!'),
            preserve_default=False,
        ),
    ]
