# Generated by Django 3.2.9 on 2021-11-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0015_auto_20211103_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='User`s ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugc.question')),
            ],
            options={
                'verbose_name': 'Answers to questions by users',
            },
        ),
    ]
