# Generated by Django 3.2.9 on 2021-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0016_answeredusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chosen_ans',
            field=models.TextField(default=0, verbose_name='Chosen answer to the question'),
        ),
    ]
