# Generated by Django 3.2.9 on 2021-11-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0017_profile_chosen_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='ansd_ques',
            field=models.TextField(default=0, verbose_name='Question is already answered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='inact_ques',
            field=models.TextField(default=0, verbose_name='Question in inactive!'),
            preserve_default=False,
        ),
    ]
