# Generated by Django 3.2.9 on 2021-11-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0019_answeredusers_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeredusers',
            name='quantity',
        ),
    ]
