# Generated by Django 3.2.9 on 2021-11-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0020_remove_answeredusers_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.PositiveIntegerField(default=0, verbose_name='Users answered'),
        ),
    ]
