# Generated by Django 3.2.9 on 2021-11-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0021_question_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredusers',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.answers'),
        ),
        migrations.AlterField(
            model_name='answeredusers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.question'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='of_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='prize',
            field=models.FloatField(verbose_name='Prize'),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.answers'),
        ),
    ]
