# Generated by Django 3.2.9 on 2021-11-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0022_auto_20211104_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default=0, verbose_name='Name of the user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.TextField(default=0, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
