# Generated by Django 3.2.9 on 2021-11-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0023_auto_20211104_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.TextField(default='RU🇷🇺', verbose_name='Chosen language'),
        ),
    ]
