# Generated by Django 3.2.9 on 2021-11-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0024_alter_profile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='select_lang',
        ),
    ]
