# Generated by Django 3.2.9 on 2021-11-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0025_remove_language_select_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='wrong',
            new_name='accepted',
        ),
    ]
