# Generated by Django 3.2.9 on 2021-11-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0026_rename_wrong_language_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='accepted',
            field=models.TextField(verbose_name='Answer is accepted'),
        ),
    ]
