# Generated by Django 3.2.9 on 2021-11-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0027_alter_language_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.TextField(default='start', verbose_name='Where is user'),
        ),
    ]
