# Generated by Django 3.2.9 on 2021-11-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0029_language_ent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='ent_phone',
            field=models.TextField(default=0, verbose_name='Enter yout phone'),
            preserve_default=False,
        ),
    ]
