# Generated by Django 3.2.9 on 2021-11-06 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0030_language_ent_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeredusers',
            options={'verbose_name': 'Answers to questions by user'},
        ),
        migrations.AlterField(
            model_name='answers',
            name='name',
            field=models.TextField(verbose_name='Text of the answer'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Number of the answer'),
        ),
        migrations.CreateModel(
            name='RightAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='User`s ID')),
                ('name', models.TextField(verbose_name='User`s name')),
                ('phone', models.TextField(verbose_name='User`s phone')),
                ('number', models.PositiveIntegerField(verbose_name='Position')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.answers')),
            ],
        ),
    ]
