# Generated by Django 3.2.9 on 2021-11-06 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0031_auto_20211106_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightanswers',
            name='question',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='ugc.question'),
            preserve_default=False,
        ),
    ]
