# Generated by Django 3.2.9 on 2021-11-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0032_rightanswers_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightanswers',
            name='send_money',
            field=models.TextField(default='No', verbose_name='Send Prize'),
        ),
    ]
