# Generated by Django 3.2.9 on 2021-11-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0033_rightanswers_send_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightanswers',
            name='send_money',
            field=models.BooleanField(default=False, verbose_name='Send Prize'),
        ),
    ]
